### PR TITLE
Phone optimization

### PR DESCRIPTION
**Pull request by schaferyan**
- [x] Top level React component should be full width on phone sized screens
- [x] Gameboard should be full width on phone-sized screens
- [x] Hamburger menu should float above content instead of pushing it down

### CODE REVIEW

**Comment by schaferyan** [comment]
The hamburger menu now floats above content when expanded, instead of pushing it down. It will need some style adjustments to look good.

**Comment by nojronatron** [comment]
As discussed, the drop-down link list in the hamburger menu looks great now, thanks!
Last item: Fix the winky-blinky links in larger view port sizes, then this will be 100% ready to go.

**Comment by schaferyan** [comment]
I added a function to respond to window-size so the links don't blink when you click them in a desktop sized screen. I'm not attached to the border.  There is probably a way to improve this from a performance perspective as well. Let me know what you think.

**Review by nojronatron — APPROVED** [review]
Looks good both in phone and desktop view! There is a weird overlap area at about 580px width where the nav items are no longer in the hamburger menu and "pop" over the content. This is very minor and can be worked on as a separate bug later.

**Pull request merged**
